customhost = "employee.cdahfwygyltw.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "yongjianching-employee"
customregion = "us-east-1"
